version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mall_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: mall
      MYSQL_USER: mall
      MYSQL_PASSWORD: mall123456
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # Redis 缓存
  redis:
    image: redis:6.2-alpine
    container_name: mall_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  # Go 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mall_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=mall
      - DB_PASSWORD=mall123456
      - DB_NAME=mall
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-secret-key
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend/config:/app/config
      - ./backend/logs:/app/logs

  # 管理后台
  admin-web:
    build:
      context: ./admin-web
      dockerfile: Dockerfile
    container_name: mall_admin_web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  # 商城前端
  mall-web:
    build:
      context: ./mall-web
      dockerfile: Dockerfile
    container_name: mall_web
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: mall_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - admin-web
      - mall-web

volumes:
  mysql_data:
  redis_data: